### ISSUE TITLE
ID review feedback

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/draft-guide-rest-client-reactjs#11]
I added ID review feedback in the attached Word doc. Let me know if you have any questions!

[rest-reactjs-guide.docx](https://github.com/OpenLiberty/draft-guide-rest-client-reactjs/files/4899323/rest-reactjs-guide.docx)

**Comment by DannyS03** [comment]
Thank you for the feedback, @Charlotte-Holt. It has been addressed (https://github.com/OpenLiberty/draft-guide-rest-client-reactjs/commit/22d983cead98cad6f91865e46df36ba78261701d) and you can review the changes. The draft site is currently refreshing. 

> Creating the React components
Change
The React library imports the react package for you to create the ArtistTable component as an inheritance of the React Component, and use its values.
To
The React library imports the react package for you to create the ArtistTable component as inheritance of the React component and use its values.

> In “React component”, I don’t think that “component” needs to be in back-ticks, based on other instances in this section.
- Here, we are referencing the main `React Component` in Reactjs and are not using "component" generically. 

> Change
Add the axios library and the getPosts() function. Next, add the componentDidMount() method into your Component.
To 
Add the axios library and the getPosts() function. Next, add the componentDidMount() method to your component.

> Question on this: It seems like the getPosts() function hostpost is pointing to the getArtistsInfo() function – is this supposed to be the case? 
- The hotspot is correct but the name was updated to the correct function name.

**Comment by Charlotte-Holt** [comment]
@DannyS03 Thanks for making updates, and understood on the two comments you made yesterday. I made just a few final comments in https://github.com/OpenLiberty/draft-guide-rest-client-reactjs/commit/22d983cead98cad6f91865e46df36ba78261701d. Could you add these updates if you agree?

**Comment by DannyS03** [comment]
@Charlotte-Holt thanks! I addressed the final comments.

**Comment by Charlotte-Holt** [comment]
@DannyS03 Thanks for addressing the feedback. This is ID approved.
