### ISSUE TITLE
Dev content review 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-rest-client-reactjs#3]
- **What you’ll learn**
  - [x] "React also allows ..." add a doc link to React
  - [x] "To learn more about React, visit: React." is no need
  - [x] "The React application in this guide was created and ..." -> "The application in this guide is provided and ..."
  - [x] "`Create React App` is a comfortable environment for learning React, ...", Why `Create React App` is backticked? Is following better?
    - "The http:...[create-React-App^] provides an environment for learning React, ..."
    - No need to have "To learn ..."
  - [x] "The REST service that provides ..." Why not just copy from AngularJS? 
    - plus "You will implement an AngularJS client..." -> "You will implement an ReactJS client"
- **Try what you’ll build**
  - [x] need to run `mvn generate-resources` before `mvn liberty-run`?
  - [x] the out is just like json. What is the benefit? Is json the final output of the finish to show?
- **Starting the service**
  - [x] do you need to explain the purpose of running `mvn generate-resources`?
- **Creating the React component**
  - [x] For "In React, a component does a specific functionality, where a web application in React is simply a collection of components. ", is following better:
    - "A React web application is simply a collection of components. Each component does a specific functionality."
  - [x] Why replace Fetchdata.js? Why not create? Then, explain import, state, and export
  - [x] format the server.xml better
- **Importing the HTTP client**
  - [x] The "In this guide, ..." statement is too complex to understand. 
  - [x] Is it necessary to mention Angular? If I want to study ReactJS, why I need to bother to learn Angular? 
  - [x] "To learn more about the axios ..." improve the sentence structure
- **Displaying the returned data**
  - [x] Need a paragraph to explain what will do in this section. Starting by componentDidMount(), I have no idea what is going on.
  - I tried finish but  http://localhost:3000 not work
- **Testing the React client**
  - [x]  "... the official React page." -> "... the official React Testing document."

**Comment by DannyS03** [comment]
- ran into an issue with the app, looking into it 👍

**Comment by DannyS03** [comment]
- **mvn generate-resources**
  - it seems like you do need to run beforehand if using dev mode. 
  - we can add a statement or two to describe, but I noticed that the angular & angularjs guide don't. 

- For `Fetchdata.js` I originally wanted to create it, but ran into issues when the file was missing while building. Looking into it again.

**Comment by DannyS03** [comment]
- ran into build issue with the app and http://localhost:3000 not working, looking into it.

**Comment by gkwan-ibm** [comment]
- **Try what you’ll build**
  - [ ] missing the output to show what the users should expect
  - [ ] the output is just like json when I ran by finish. Would you explain to me "What is the benefit of using ReactJS?" The AngularJS at least convert the json to some text. Can ReactJS do similar thing as AngularJS?
- **Creating the React component**
  - [ ] "... export from the react package,..." -> "...export from the `react` package,..."
  - [ ] why "Create the Fetchdata.js" and then update it?
  - [ ] format the server.xml better for the `<httpEndpoint/>` and algin `<cors/>`
- **Importing the HTTP client**
  - [ ] The "In this guide, ..." statement is too complex to understand.
  - [ ]  "To learn more about the axios ... see: axios." improve the sentence structure. Use colon not our practice.
- **Displaying the returned data**
  - [ ]  Need a paragraph to explain what will do in this section. Starting by componentDidMount(), I have no idea what is going on.
  - [ ] I tried finish but http://localhost:3000 not work
- **Testing the React client**
   - [ ]  "...the official React testing document." Suggest the link highlight "React testing document" instead of "React" only

**Comment by DannyS03** [comment]
- feedback addressed; just need to add some edits. 
- draft guide is also available on the **lgdev** site at `:4020`.

**Comment by gkwan-ibm** [comment]
@DannyS03 
- **Getting started**
  - [ ] output of the json should be formatted better instead of 1 line. No need to show all. 
  - [ ] screen shot should do better, e.g. include "Artist Web Service", reduce the space between the table and paging section
- **Creating the React component**
  - [ ] **Building the frontend** -> **Running the frontend**
  - [ ] should "Also, because you ...CORS..."  be done in the "Starting and running the backend service" section?
    - [ ] if keep in here, may need a subsection for it
- [ ] server.xml, `httpsPort=` should be indented by 4 spaces as well as the attributes of `cors/>`

**Comment by DannyS03** [comment]
- new screenshot for the react table has line from the browser at the bottom: for better separation of the image from the proceeding paragraph.

**Comment by DannyS03** [comment]
- new feedback addressed. 
  - @gkwan-ibm can verify changes. 

- the `artist.json` includes the same data from the application in the rest client java, angularjs, angular guides, with some additions. The `album` data for each artist currently does not display on the react table... only the additional artists attributes do. 
  - We could delete the data that is not used from the original json file implementation .
  - We could change the output to focus on the albums of each artist (but I thought it would be a good idea to output something different as there are three guides that generate the same outcome already, but through different means).
  - Everything could be outputted (this may make complicate the app unnecessarily).

**Comment by gkwan-ibm** [comment]
@DannyS03 
- Need to investigate how to package/deploy ReactJS as an app running by OL

**Comment by DannyS03** [comment]
- rest client application simplified and reflects the same application as in the angularjs guide
- frontend & backend now execute as “single execution” and depend on the OL server.
- paginated table updated to reflect the album JSON array in artists.json

**Comment by gkwan-ibm** [comment]
@DannyS03 
- **Try what you’ll build**
  - [ ] http://localhost:9080 returned "Error 404: SRVE0190E: File not found: / "
  - [ ] no need to have the following?
    - "Also, pressing CTRL+C in the shell session that deploys the frontend application will stop the node server."
- [ ] after I stopped the liberty:run, I went to start directory and run `mvn generate-resources` got errors
- **Starting the service**
  - [ ] usually we replace instead of update
- **Creating the React component**
  - [ ] precreate directory src/main/frontend/src/Components/
- **Importing the HTTP client**
  - [ ] usually we replace instead of update
- **Displaying the returned data**
  - [ ] usually we replace instead of update
  - [ ] http://localhost:9080 returned "Error 404: SRVE0190E: File not found: / "

will review again after address the above

**Comment by DannyS03** [comment]
- addressed feedback.
  - app under finish directory will be ran from just starting the OL server and the required production build static files are already configured in `webapp/static`. This favours the approach that the app in the finish dir should be "finished", and the user does not need to worry about generating the node resources to create the frontend build when they are in the **twyb** section.
  - Refactored and cleaned up files as the issue was the static files being created by generated the node resources (hence creating the production build) were not being passed on properly. 
 
- CORS filter removed from `server.xml` as the frontend and backend is now being hosted off of the OL server and not needed. README also updated.
- The reason **mvn generate-resources** is failing is because the `npm run build` resource cannot execute as it is looking for the `Fetchdata.js` file, which is to be created in the guide rather than updated.
  - The angular guide does not "create" it's module files but rather updates them throughout the guide... see, https://openliberty.io/guides/rest-client-angular.html#importing-the-http-client & https://github.com/OpenLiberty/guide-rest-client-angular/blob/master/start/src/main/frontend/src/app/app.module.ts
  - We could either tell the user to build the frontend later on in the guide, or have `Fetchdata.js` included in the start dir as it used to be.

**Comment by gkwan-ibm** [comment]
- [ ] app not work on finish and start
- [ ] restructure the flow, just create Fetchdata.js once and explain the detail by multiple subsection - run mvn generate-resources later
- [ ] or precreate a simple Fetchdata.js and ask readers to replace (still replace one) - then we can ask readers to run the mvn generate-resources before liberty:dev
- [ ] add more content to showcase the change of the artists.json

**Comment by DannyS03** [comment]
> 
> 
>     * [ ]  app not work on finish and start
> 
>     * [ ]  restructure the flow, just create Fetchdata.js once and explain the detail by multiple subsection - run mvn generate-resources later
> 
>     * [ ]  or precreate a simple Fetchdata.js and ask readers to replace (still replace one) - then we can ask readers to run the mvn generate-resources before liberty:dev
> 
>     * [ ]  add more content to showcase the change of the artists.json

- tried on another machine with fresh env and clone in finish and start (not in the current approach in the guide) and it works.
![image](https://user-images.githubusercontent.com/25497083/82703652-58371180-9c42-11ea-8934-3df9ab5a18b4.png)

- other feedback is being addressed .

**Comment by gkwan-ibm** [comment]
- [ ] add a new section "Setting project configuration"
  - need to explain what you did in the pom.xml for generate reactjs files and copy the generated files to OL
- [ ] create src/main/frontend/src/Components directory + .gitkeep 
- [ ] Add a statement/paragraph to say ReactJS front end applciation including java scripts, image files, and style sheet files are provided.
- [ ] rewrite the flow  
  - create index.js, App.js, Fetchdata.js
  - simpfy Fetchdata.js
  - focus on how the reactjs commincate with the REST client
- create a branch from dev to xxx for saving what you did
  - update the dev bracnh for the above
- **Testing the React client**
  - dup content "Likewise, pressing CTRL+C..."
- [ ] after mvn generate resources, the app not work in start directory
- [ ] remove "Optional: Updating the REST service" section

**Comment by DannyS03** [comment]
- flow rewritten and feedback addressed.

**Comment by gkwan-ibm** [comment]
@DannyS03 
- **Project Configuration**
  - [ ] no need to have "Server side" subsection
  - [ ] because the "node resources" and "Maven resource plugin" content have too many lines, suggest not to update. Also, update pom.xml, need restart dev mode?. Suggest just simply say the pom.xml is provided for you. Then explain both content. It is fine for this section is short and has no command to do
  - [ ] "Client side" can be a section as "Creating the default page"
    - [ ] "You will need to create..." -> "You need to create..."
    - [ ] the path in "Create the index.js file." is wrong
    - [ ] hotspot `unregistered` does not highlight correctly
    - [ ] remove the hotspot for `index.js` at the end
    - [ ] src/main/frontend/src/index.js is no need in the start directory because you ask reader to create it
- **Creating the React components**
  - [ ] Suggest following order:
    - "The main component ... You will need to create ..."
    - "Create the App.js file." action
    - "The App.js file returns the ..."
    - "Next, you will create ..."
  - [ ] The update action is too long and the hotspot move back and fore (confuse reader). Suggest the update action should just ask reader to add xxx, yyy, zzz. Then outside the action you can explain the detail
  - [ ] "Building the frontend" should be a main section instead of subsection

**Comment by DannyS03** [comment]
Addressed your feedback @gkwan-ibm. You can review changes.

**Comment by DannyS03** [comment]
Draft site is updated with latest changes.

**Comment by gkwan-ibm** [comment]
- **Project Configuration**
  - [ ] rewrite both statements to explain clearly
    - "The static files" readers may not know what you are talking about
    - in general, I guess readers may not understand the first statment
    - in second statement, readers may not know target directory, should say something like "copy the generated ReactJS files to the web content of the application"
  - [ ] The subsection "**Creating the default page**" should be a main section
     - [ ]  the path in "Create the index.js file." is still wrong
- **Creating the React components**
  - [ ] "The `return` statement ..." The hotspot of `return` should cover the line `);` too
- [ ] don't know why the start directory not work again by following the instruction
  - the static directory with other files were not copied to the `src\main\webapp directory`

**Comment by DannyS03** [comment]
>     * **Project Configuration**
>       
>       * [ ]  rewrite both statements to explain clearly
>         
>         * "The static files" readers may not know what you are talking about
>         * in general, I guess readers may not understand the first statment
>         * in second statement, readers may not know target directory, should say something like "copy the generated ReactJS files to the web content of the application"
>       * [ ]  The subsection "**Creating the default page**" should be a main section
>         
>         * [ ]   the path in "Create the index.js file." is still wrong
> 
>     * **Creating the React components**
>       
>       * [ ]  "The `return` statement ..." The hotspot of `return` should cover the line `);` too
> 
>     * [ ]  don't know why the start directory not work again by following the instruction
>       
>       * the static directory with other files were not copied to the `src\main\webapp directory`

- Regarding the path in "Create the index.js file." isn't it `src/main/frontend/src`?
- Figuring out why static files are not being served properly in `start` dir.

**Comment by DannyS03** [comment]
- application needs to be packaged and have mvn execute the in order for static files to be copied over properly. `mvn package` will execute all the required phases. Originally, when running `mvn generate-resources` the files were still being copied from the main/frontend/build dir to main/webapp but it looks like this is not the reliable/appropriate method. 
  - **mvn generate-resources** changed to **mvn package**, and running `generate-resources` goal alone is still explained. 
  - section title may need to be reconsidered.


Ready for review.

**Comment by gkwan-ibm** [comment]
- **Project Configuration**
  - [ ] The content not clear. Suggest e.g. "The maven project is configured in order to do ... . Use `frontend-maven-plugin` to .... Use `maven-resources-plugin` to ..."
    - need to figure out the steps in below first
  - [ ] format the pom.xml better to have no wrapped line
- **Creating the default page**
  - [ ] in the create index.js command, `src/main/frontend/src` -> `src/main/frontend/src/ index.js`
- **Creating the React components**
  - [ ] some places in Fetchdata.js are not aligned correct, e.g. content of `columns` and `return`
- **Building and packaging the frontend**
  - [ ] To run `mvn package` at the end to make the app work is not the best approach and `package` has a sense of completion (not for developing). Would you study and make the following order?
    1. run a command (better not `mvn package`) to generate/copy the static directory to the src\main\webapp directory
    1. `mvn liberty:dev`
       - (a. and b. can be switched)
    1. create all index.js, App.js, and Fetchdata.js
    1. run another command if necessary
    1. hit http://localhost:9080

**Comment by DannyS03** [comment]
- In that case, I will use `mvn process-resources` which is exactly what we are trying to achieve with generating the node resources and copying them into the web content. The steps will stay the same in this case as they do not need to be altered.

**Comment by gkwan-ibm** [comment]
- **Project Configuration**
  - is node == Node.js? 
    - [ ] use Node or Node.js instead of node
    - [ ] At the beginning, need to explain a bit Node.js (may need a link to Node.js doc) and use Node.js for the frontend of the application and the relationship with ReactJS
  - [ ] suggest following:
    - The [hotspot to the whole plugin]`frontend-maven-plugin` is used to [hotspot as is]`install` Node.js/Node in your [hotspot to workingDirectory]`project directory` and [hotspot as is]`produce` the frontend production build at the `src/main/frontend/build` directory.
    - Then, the [hotspot to the whole plugin]`maven-resources-plugin` copies the static content from the frontend [hotspot as is]`build` directory to the [hotspot as is]`web content` of the application.
- in pom.xml, 
  - [ ] remove `<failOnMissingWebXml/>`
  - [ ] remove ` <!-- Support for JDK 9 and above -->` and the dependecy
  - [ ] update liberty-maven-plugin to use 3.2.1
  - [ ] no test, so no need to have all test dependencies except `junit-jupiter` (not `junit-jupiter-engine`)

**Comment by DannyS03** [comment]
- Addressed. Originally, I did not include information about node as we did not have the project configuration section.

**Comment by gkwan-ibm** [comment]
- **Project Configuration**
  - [ ] no need to backtick the word Node.js
  - [ ] "... see the official (Node.js Documentation." -> "... see the official Node.js documentation."
- **Building and packaging the frontend**
  - [ ] move "When you are done checking the application root, ..." at the end of the "Testing the React client" section

**Comment by gkwan-ibm** [comment]
- **What you’ll learn**
  - [ ] "The React application in this guide is provided and configured for you in the `frontend` directory." Should update the `frontend` to `src/main/frontend`?
  - [ ] "You will implement a ReactJS client that consumes this JSON and displays its contents on a single-page webpage, which will act as your application’s frontend." -> "For simplicity, you will implement a ReactJS client as the frontend of the application that consumes this JSON and displays its contents on a single-page webpage."
- **Starting the service**
  - [ ] Update the paragraph "Note: all the other dependencies ..." 
    - at least the paths are incorrect
- **Project Configuration**
  - The first statement not clear
    - now is not "frontend application", frontend is the frontend of the application?
    - what does "on the same origin." mean?
  - Consider the following:
    - start by this paragraph "The frontend of your application uses Node.js to..." 
    - "The Maven project is configured for you to install Node.js and populate production files to the web content of the application."
    - "The [hotspot]`frontend-maven-plugin` plugin is used to [hotspot]`install` Node.js in the [hotspot]`working` directory, and [hotspot]`produce` the production files to the `src/main/frontend/build` directory."
    - "Then, the [hotspot]`maven-resources-plugin` copies the `static` content from the [hotspot]`build` directory to the [hotspot]`web content` of the application."
- **Creating the default page**
  - [ ] "You need to create the entry point of your React application. In production, when the frontend application is used by other applications, the index.js file should be the main entry point of the application as it coincides with the index.html file. ..." -> "You need to create the entry point of the application. The [hotspot]`index.js` file should be the main entry point of the frontend of the application as it coincides with the `index.html` file. ..."
  - [ ] "The `React library` imports the `default export` from the react package. " -> "The [hotspot]`React` library imports the default export from the [hotspot]`react` package. "
     - also what is "default export" mean?
  - [ ] "... file included in `frontend/src.`" `frontend/src` is incorrect now
  - [ ] what is `create-react-app`?
- **Creating the React components**
  - [ ] "Next, ... your react webpage." -> "Next, ... your React webpage."
  - [ ] "The `React library` imports the `default export`..." -> "The `React` library imports the `default export`..."
  - [ ] "... an inheritance of the `React Component`. " ->  "... an inheritance of the `React` component`. "???
- **Importing The HTTP client**
  - [ ] "Add the `axios library` ..." -> "Add the `axios` library ..."
- **Building and packaging the frontend**
  - [ ] "Navigate to the http://localhost:9080 URL to view your frontend application." -> "Navigate to the http://localhost:9080 URL to view the frontend of your application."
- **Testing the React client**
  - [ ] `create-react-app` what does it mean?
  - [ ] "...which is included in `frontend/src`. " `frontend/src` is incorrect now

_Note: Overall comments for the above_
  - make "frontend" clear to the readers
  - `frontend` directory changed, so make sure the content updated correctly
  - mention `create-react-app` in the readme several times but I cannot find out what it is? how it relates?

**Comment by DannyS03** [comment]
- `create-react-app` is explained in **What you'll learn**
<img width="555" alt="image" src="https://user-images.githubusercontent.com/25497083/83926229-4fbcfb80-a757-11ea-9ad6-e4ac52de4e55.png">

- better to keep 
  - "... an inheritance of the `React Component`. "
  - to simplify and not go into detail about `default exports` and `named exports`, I changed to: 
#### Creating the default page
```
The [hotspot=import-react]`React` library imports the [hotspot=import-react]`react` package.
```

---

#### Creating the React components
```
The [hotspot=react-library file=1]`React library` imports the `react` package for you to create the [hotspot=class file=1]`Fetchdata` component as an inheritance of the `React Component`, and use its values.
```
