### ISSUE TITLE
readme instructions 

### ISSUE THREAD

**Issue by seanwayland** [OpenLiberty/draft-guide-rest-client-reactjs#4]
The readme suggests pointing to port 8080 in the install test but it should be 
http://localhost:3000/

**Comment by yeekangc** [comment]
@DannyS03 @gkwan-ibm

**Comment by DannyS03** [comment]
@seanwayland Thank you for pointing out the disparity. The port had been temporarily declared in the package.json for testing purposes. README was updated; closing for now.
