### ISSUE TITLE
nth-check vulnerability

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/draft-guide-rest-client-reactjs#80]
address https://github.com/OpenLiberty/guide-rest-client-reactjs/security/dependabot

based on https://issueexplorer.com/issue/facebook/create-react-app/11647. This issue is pending on https://github.com/facebook/create-react-app/pull/11780

**Comment by jakub-pomykala** [comment]
This alert can be dismissed - after doing some research I have tested it by moving `react-scripts` into `devDependencies` and running `npm audit --production` which returns:
```
found 0 vulnerabilities
```

This fix can be found [here](https://github.com/facebook/create-react-app/issues/11174)

**Comment by gkwan-ibm** [comment]
close
- the guide was updated and has no vulnerability now
